### ISSUE TITLE
Carousel navigation dots on home page banner

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#103]
Hi Team, 

Business requirements is carousel navigation dots on home page banner. Increase the speed banner slide. 
![image](https://user-images.githubusercontent.com/112628085/216012248-7767d38c-a0c0-49bb-bc31-71cdf4bc6309.png)

**Comment by asthabh23** [comment]
@2016DigiTech , changes for this can be done in slideshow block.

**Comment by rofe** [comment]
@2016DigiTech For inspiration, take a look at this carousel implementation on another Franklin project:
https://github.com/hlxsites/rxbar/tree/main/blocks/carousel

You can see it in action [here](https://main--rxbar--hlxsites.hlx.live/)
