### ISSUE TITLE
Contact lead form drop to Email ID. 

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#104]
Hi Team, 

An email trigger with lead form information from contact form should go to following email ids in real time.
kamini.sharma@tlcgroup.com, shailendra@tlcgroup.com, nrapendra.mishra@tlcgroup.com, azam.md@tlcgroup.com

**Comment by asthabh23** [comment]
@2016DigiTech This can be achieved easily by making the relevant settings in the sheet from menu (as in screenshot)
![Screenshot 2023-02-09 at 1 27 12 PM](https://user-images.githubusercontent.com/76686725/217751963-d6ea5ce6-978a-4c1d-8325-05c2293aebe3.png)

**Comment by 2016DigiTech** [comment]
Hi Team, 

We are already using this notification but we wanted email trigger with lead details in the mail body.

**Comment by rofe** [comment]
This is currently not supported by Franklin. Suggest to look for 3rd party automation for Google Drive.
