### ISSUE TITLE
Logo fetch from the url on home page right bottom side. 

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#106]
Hi Team, 

We need to fetch our cortication logo of DUNS from this url 

<script language="JavaScript" src="https://dunsregistered.dnb.com/" type="text/javascript" ></script> 

this need to be only on the home page footer right side corner,

**Comment by rofe** [comment]
See `delayed.js` to learn how to load an external script from within an ES module.
