### ISSUE TITLE
New Design development for New Table Reservation Page.  

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#107]
Hi Team,

Please develop the flow chart as per the design 
1. Customer journey section 
2. Hotel Journey Section 

https://www.figma.com/proto/IqZ8vXxpcsCLqs6H65ntY9/Sub-Pages-TLC-Website?node-id=106%3A11&scaling=scale-down&page-id=58%3A40&starting-point-node-id=106%3A11&show-proto-sidebar=1

**Comment by asthabh23** [comment]
@2016DigiTech , the separate steps in the two sections should be created as separate images at your end and then those images can be directly used and styled using `Cards` block

**Comment by 2016DigiTech** [comment]
Hi Team,

Please advise on Carouse on Mobile Layout. 

https://app.zeplin.io/project/63e5dc2e40acc9197d19338e/screen/63e5e7d9182363189a6ec3c6
