### ISSUE TITLE
Google Tag Manager Integration on TLC Website. 

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#110]
Hi Team, 

Please add updated tag manager script as per the below script. 

Copy the code below and paste it onto every page of your website.
Paste this code as high in the <head> of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-W64FJ7M');</script>

Additionally, paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-W64FJ7M"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

**Comment by rofe** [comment]
@2016DigiTech see https://github.com/hlxsites/tlcgrp/blob/main/scripts/delayed.js#L26-L35
