### ISSUE TITLE
Add google tag code 

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#122]
Hi team
Please add following code. 

Property Name: TLC DigiTech ([www.tlcgroup.com](http://www.tlcgroup.com/)) (Website) 

Google Tag Manager: Copy the code below and paste it onto every page of the website.

Paste this code as high in the <head> of the page as possible:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-58VC5NG');</script>

Additionally, paste this code immediately after the opening <body> tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-58VC5NG"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

 

Google Analytics (GA4) (MEASUREMENT ID - G-ZE1NRYD0CR ) : Install the Google tag manually - Copy and paste it in the code of every page of the website, immediately after the <head> element. Don’t add more than one Google tag to each page.

 <script async src="https://www.googletagmanager.com/gtag/js?id=G-ZE1NRYD0CR"></script> <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-ZE1NRYD0CR'); </script>

**Comment by rofe** [comment]
@2016DigiTech please verify that data is arriving as expected on the Google side:

https://issue-122--tlcgrp--hlxsites.hlx.page/
