### ISSUE TITLE
Hyper link open in new tab

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#87]
Hi Team

Business Requirement >In contact us form we need hyper link and also open in new window (I agree to the **[Terms]**(https://tlcgroup.com/payment-terms) and the **[Privacy Policy]**(https://tlcgroup.com/privacy-policy) on this website by offering the content above and give permission to TLC DigiTech Pvt. Ltd to make contact with me to receive more information. )

Hyper link > Terms and Privacy Policy
![term and privacy policy ](https://user-images.githubusercontent.com/112628085/208885183-4fd41d1a-679f-4f77-8a6d-d873f45093aa.png)

**Comment by rofe** [comment]
Fixed via #86
