### ISSUE TITLE
Form submission failure in the first time

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#95]
Hi Team, 

In some cases when user click on submit button on contact form after filling the all required information in show failure error. 
![image](https://user-images.githubusercontent.com/112628085/213378108-50422676-570c-45bc-9356-e4c271fbb13c.png)

**Comment by rofe** [comment]
@2016DigiTech please check the recaptcha settings. The API still gets loaded, but the client side token is no longer created. Mitigation: disable server side validation 

@sarveshguptaTLC

**Comment by rofe** [comment]
I think this one can be resolved for now.
