### ISSUE TITLE
Country code in contact form 

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#96]
Hi Team, 

We need to add country code in mobile number section of the contact form. Also create a choice box as per the design.  Please check the design
![image](https://user-images.githubusercontent.com/112628085/213662314-fa48de85-804f-4c86-bd7d-03e517aa74bf.png)

**Comment by rofe** [comment]
@2016DigiTech can you please add a design mockup how this should look like?

**Comment by asthabh23** [comment]
@2016DigiTech we are still waiting for a design mockup as mentioned by @rofe in the above comment.

**Comment by asthabh23** [comment]
@2016DigiTech Below link can be used for reference to get country code part in place:
https://www.twilio.com/blog/international-phone-number-input-html-javascript
