### ISSUE TITLE
Contact lead drop to email id

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#97]
Hi Team, 

Need to contact from drop in email ids. 

shailendra@tlcgroup.com
kamini.sharma@tlcgroup.com
nrapendra.mishra@tlcgroup.com
azam.md@tlcgroup.com

**Comment by rofe** [comment]
You can subscribe to get notified of changes in the target sheet with your email address:
Open the sheet, select Tools > Notification settings > Edit notifications, and pick your favorite way of being notified.
