### ISSUE TITLE
Thank you page

### ISSUE THREAD

**Issue by 2016DigiTech** [hlxsites/tlcgrp#99]
Hi Team, 

Please create a thank you page for all lead drops. Please check the design. Please check below zeplin url for design. 
https://app.zeplin.io/project/63d8e47e3dd2a811fef066aa

![image](https://user-images.githubusercontent.com/112628085/213662587-50aad2e0-802e-46a0-a531-4b7a312a3421.png)

**Comment by rofe** [comment]
@2016DigiTech the thank you page is here: https://www.tlcgroup.com/contact-us/thank-you. You can make these changes in the content, no code chage required.
